// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using lab_1_Nyesteban.DAL;

#nullable disable

namespace lab_5x_Nyesteban.Migrations
{
    [DbContext(typeof(StoreContext))]
    [Migration("20230509165846_user_roles")]
    partial class user_roles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-preview.2.23128.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("lab_1_Nyesteban.Models.App", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("AppDescription")
                        .HasColumnType("text");

                    b.Property<string>("AppName")
                        .HasColumnType("text");

                    b.Property<decimal>("AppPrice")
                        .HasColumnType("numeric");

                    b.Property<int>("AppRating")
                        .HasColumnType("integer");

                    b.Property<int>("AppSize")
                        .HasColumnType("integer");

                    b.Property<string>("AppVersion")
                        .HasColumnType("text");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("UserID");

                    b.ToTable("Apps");
                });

            modelBuilder.Entity("lab_1_Nyesteban.Models.Company", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("CompanyDescription")
                        .HasColumnType("text");

                    b.Property<int>("CompanyEstablishmentYear")
                        .HasColumnType("integer");

                    b.Property<string>("CompanyName")
                        .HasColumnType("text");

                    b.Property<decimal>("CompanyRating")
                        .HasColumnType("numeric");

                    b.Property<decimal>("CompanyRevenue")
                        .HasColumnType("numeric");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("UserID");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("lab_1_Nyesteban.Models.DevelopmentDetail", b =>
                {
                    b.Property<int>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<int>("AppId")
                        .HasColumnType("integer");

                    b.Property<decimal>("DevelopmentCosts")
                        .HasColumnType("numeric");

                    b.Property<int>("DevelopmentTimeInHours")
                        .HasColumnType("integer");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.HasKey("CompanyId", "AppId");

                    b.HasIndex("AppId");

                    b.HasIndex("UserID");

                    b.ToTable("DevelopmentDetails");
                });

            modelBuilder.Entity("lab_1_Nyesteban.Models.Game", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int?>("CompanyID")
                        .HasColumnType("integer");

                    b.Property<string>("GameDescription")
                        .HasColumnType("text");

                    b.Property<int>("GameLength")
                        .HasColumnType("integer");

                    b.Property<string>("GameName")
                        .HasColumnType("text");

                    b.Property<decimal>("GameRating")
                        .HasColumnType("numeric");

                    b.Property<int>("GameSize")
                        .HasColumnType("integer");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("CompanyID");

                    b.HasIndex("UserID");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("lab_5x_Nyesteban.Models.RegistrationCode", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("code")
                        .HasColumnType("text");

                    b.Property<DateTime?>("generatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ID");

                    b.ToTable("RegistrationCodes");
                });

            modelBuilder.Entity("lab_5x_Nyesteban.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EMail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RealName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("lab_1_Nyesteban.Models.App", b =>
                {
                    b.HasOne("lab_5x_Nyesteban.Models.User", "User")
                        .WithMany("Apps")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("lab_1_Nyesteban.Models.Company", b =>
                {
                    b.HasOne("lab_5x_Nyesteban.Models.User", "User")
                        .WithMany("Companies")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("lab_1_Nyesteban.Models.DevelopmentDetail", b =>
                {
                    b.HasOne("lab_1_Nyesteban.Models.App", "App")
                        .WithMany("DevelopmentDetails")
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("lab_1_Nyesteban.Models.Company", "Company")
                        .WithMany("DevelopmentDetails")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("lab_5x_Nyesteban.Models.User", "User")
                        .WithMany("DevelopmentDetails")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("App");

                    b.Navigation("Company");

                    b.Navigation("User");
                });

            modelBuilder.Entity("lab_1_Nyesteban.Models.Game", b =>
                {
                    b.HasOne("lab_1_Nyesteban.Models.Company", null)
                        .WithMany("Games")
                        .HasForeignKey("CompanyID");

                    b.HasOne("lab_5x_Nyesteban.Models.User", "User")
                        .WithMany("Games")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("lab_1_Nyesteban.Models.App", b =>
                {
                    b.Navigation("DevelopmentDetails");
                });

            modelBuilder.Entity("lab_1_Nyesteban.Models.Company", b =>
                {
                    b.Navigation("DevelopmentDetails");

                    b.Navigation("Games");
                });

            modelBuilder.Entity("lab_5x_Nyesteban.Models.User", b =>
                {
                    b.Navigation("Apps");

                    b.Navigation("Companies");

                    b.Navigation("DevelopmentDetails");

                    b.Navigation("Games");
                });
#pragma warning restore 612, 618
        }
    }
}
